# Generated by Django 2.2.10 on 2021-02-10 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210210_2021'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='answer',
            unique_together={('poll', 'question', 'answered_by')},
        ),
    ]
